# This is a Github Workflow that waits for quality and security to be executed
# on the `main` branch.

# If everything pass it also release all package using Semantic Release.

name: Release

on:
  push:
    branches:
      - main

env:
  FREEZER_TOKEN: ${{ secrets.FREEZER_TOKEN }}
  NODE_ENV: production

jobs:
  release:
    name: Releasing updated packages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.MACHINE_GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn

      - name: Setting up dependencies & workspaces
        run: yarn install --immutable --immutable-cache && yarn run -T setup

      - name: Setting up Git to access Freezer
        run: yarn run setup-freezer

      - name: Building all packages
        run: yarn run -T build

      - name: Waiting for security to pass
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          check-name: Checking Yarn cache's integrity
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Waiting for quality to pass
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          check-name: Checking code quality
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Publishing updated public packages to NPM, Git & GitHub
        env:
          GH_TOKEN: ${{ secrets.MACHINE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.MACHINE_NPM_TOKEN }}
          GIT_AUTHOR_NAME: '@snowball-tech-bot'
          GIT_AUTHOR_EMAIL: snowball-bot@snowball.xyz
          GIT_COMMITTER_NAME: '@snowball-tech-bot'
          GIT_COMMITTER_EMAIL: snowball-bot@snowball.xyz
        run: yarn run -T publish-all
