# This is a Github Workflow that runs lint, formatter and unit tests on every
# push and pull request.

# If everything pass and we are on the `main` branch, it also runs Semantic
# Release.

name: CI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release updated packages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.MACHINE_GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Installing dependencies
        run: yarn install --immutable --immutable-cache

      - name: Starting TurboRepo local cache server
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Building all packages
        run: yarn turbo run build

      - name: Wait for quality to pass
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: Checking code quality
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Publishing updated packages to NPM, Git and GitHub
        env:
          GH_TOKEN: ${{ secrets.MACHINE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.MACHINE_NPM_TOKEN }}
          GIT_AUTHOR_NAME: '@snowball-tech-bot'
          GIT_AUTHOR_EMAIL: snowball-bot@snowball.xyz
          GIT_COMMITTER_NAME: '@snowball-tech-bot'
          GIT_COMMITTER_EMAIL: snowball-bot@snowball.xyz
        run: yarn publish:all
